---
services:
  mariadb:
    environment:
      - MYSQL_DATABASE=webapp
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
